version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ems-app:latest
    container_name: ems_app_container
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DB_ENGINE: django.db.backends.mysql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: database
      DB_PORT: "3306"
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - type: volume
        source: app-data
        target: /usr/src/app/staticfiles
    networks:
      - app-network
  database:
    image: mysql:8.0
    container_name: ems_database_container
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - app-network
volumes:
  app-data:
    driver: local
  database-data:
    driver: local
networks:
  app-network:
    driver: bridge